[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
deploy = "8e4Xi3gmt3cgTymHhzTihUabK9rRixfy7C8MEd7EvxYo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./wallets/deploy-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
