[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
deploy = "GJbPXcyarfqAByXu7hk8znR2M4wJs6EZM7jh6stJMUqL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./wallets/deploy-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
